name: flec
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - python=3
  - pip
  - trimmomatic
  - bwa
  - samtools ==1.9
  - velvet
  - blast
  - trinity
  - exonerate
  - cd-hit
  - java-jdk
  - pip:
    - git+https://github.com/Ulises-Rosas/aTRAM.git#egg=atram[complete]
    - git+https://github.com/Ulises-Rosas/FishLifeExonCapture.git#egg=fishlifeexoncapture
